### ISSUE TITLE
Add browser notifications

### ISSUE THREAD

**Issue by wh1zk1d** [wh1zk1d/pomo#1]
Show a browser notification when a pomodoro is finished.

**Comment by chefk5** [comment]
Will take a look.

**Comment by ahmedibrahim404** [comment]
let me know, if I can work on this

**Comment by wh1zk1d** [comment]
Sorry @ahmedibrahim404, @chefk5 was first

**Comment by chefk5** [comment]
What should the notification say?

**Comment by wh1zk1d** [comment]
Something like "Pomodoro complete, time for a break!" would be nice

**Comment by chefk5** [comment]
#11 My fix
