### ISSUE TITLE
Add more emojis

### ISSUE THREAD

**Issue by wh1zk1d** [wh1zk1d/pomo#2]
Add your favorite emoji to the RandomEmoji Component (/src/components/RandomEmoji.js).
Please make sure that the emoji isn't already in the list.

**Comment by Eddievin** [comment]
Hey, can I do this?

**Comment by wh1zk1d** [comment]
Sure @Eddievin

**Comment by Eddievin** [comment]
Is there a limited number of emojis I should add? or as many as possible.

**Comment by wh1zk1d** [comment]
Please add only one, so others can add some too :)

**Comment by Eddievin** [comment]
only one?, haha okay. It is done. let me create a pull request.
